//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CafeCMU.Module.BusinessObjects.ORMDataModel1
{

    public partial class Bangluong : XPObject
    {
        Nhanvien fNhanvienID;
        [Association(@"BangluongReferencesNhanvien")]
        public Nhanvien NhanvienID
        {
            get { return fNhanvienID; }
            set { SetPropertyValue<Nhanvien>(nameof(NhanvienID), ref fNhanvienID, value); }
        }
        string fNam;
        public string Nam
        {
            get { return fNam; }
            set { SetPropertyValue<string>(nameof(Nam), ref fNam, value); }
        }
        string fThang;
        public string Thang
        {
            get { return fThang; }
            set { SetPropertyValue<string>(nameof(Thang), ref fThang, value); }
        }
        string fSogiolam;
        public string Sogiolam
        {
            get { return fSogiolam; }
            set { SetPropertyValue<string>(nameof(Sogiolam), ref fSogiolam, value); }
        }
        string fLuong;
        public string Luong
        {
            get { return fLuong; }
            set { SetPropertyValue<string>(nameof(Luong), ref fLuong, value); }
        }
    }

}
