//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CafeCMU.Module.BusinessObjects.ORMDataModel1
{

    public partial class HoadonCT : XPObject
    {
        Hoadon fHoadonID;
        [Association(@"HoadonCTReferencesHoadon")]
        public Hoadon HoadonID
        {
            get { return fHoadonID; }
            set { SetPropertyValue<Hoadon>(nameof(HoadonID), ref fHoadonID, value); }
        }
        Sanpham fSanphamID;
        [Association(@"HoadonCTReferencesSanpham")]
        public Sanpham SanphamID
        {
            get { return fSanphamID; }
            set { SetPropertyValue<Sanpham>(nameof(SanphamID), ref fSanphamID, value); }
        }
        string fSoluong;
        public string Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<string>(nameof(Soluong), ref fSoluong, value); }
        }
        string fDongia;
        public string Dongia
        {
            get { return fDongia; }
            set { SetPropertyValue<string>(nameof(Dongia), ref fDongia, value); }
        }
        string fThanhtien;
        public string Thanhtien
        {
            get { return fThanhtien; }
            set { SetPropertyValue<string>(nameof(Thanhtien), ref fThanhtien, value); }
        }
        [Association(@"TieuhaoReferencesHoadonCT"), Aggregated]
        public XPCollection<Tieuhao> Tieuhaos { get { return GetCollection<Tieuhao>(nameof(Tieuhaos)); } }
    }

}
