//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CafeCMU.Module.BusinessObjects.ORMDataModel1
{

    public partial class Phieunhap : XPObject
    {
        Nhacungcap fNCCID;
        [Association(@"PhieunhapReferencesNhacungcap")]
        public Nhacungcap NCCID
        {
            get { return fNCCID; }
            set { SetPropertyValue<Nhacungcap>(nameof(NCCID), ref fNCCID, value); }
        }
        Nhanvien fNhanvienID;
        [Association(@"PhieunhapReferencesNhanvien")]
        public Nhanvien NhanvienID
        {
            get { return fNhanvienID; }
            set { SetPropertyValue<Nhanvien>(nameof(NhanvienID), ref fNhanvienID, value); }
        }
        string fSo;
        public string So
        {
            get { return fSo; }
            set { SetPropertyValue<string>(nameof(So), ref fSo, value); }
        }
        string fNgay;
        public string Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<string>(nameof(Ngay), ref fNgay, value); }
        }
        [Association(@"DongnhapReferencesPhieunhap"), Aggregated]
        public XPCollection<Dongnhap> Dongnhaps { get { return GetCollection<Dongnhap>(nameof(Dongnhaps)); } }
    }

}
