//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CafeCMU.Module.BusinessObjects.ORMDataModel1
{

    public partial class Sanpham : XPObject
    {
        NhomSP fNhomID;
        [Association(@"SanphamReferencesNhomSP")]
        public NhomSP NhomID
        {
            get { return fNhomID; }
            set { SetPropertyValue<NhomSP>(nameof(NhomID), ref fNhomID, value); }
        }
        string fTenSP;
        public string TenSP
        {
            get { return fTenSP; }
            set { SetPropertyValue<string>(nameof(TenSP), ref fTenSP, value); }
        }
        string fDvt;
        public string Dvt
        {
            get { return fDvt; }
            set { SetPropertyValue<string>(nameof(Dvt), ref fDvt, value); }
        }
        string fGiaban;
        public string Giaban
        {
            get { return fGiaban; }
            set { SetPropertyValue<string>(nameof(Giaban), ref fGiaban, value); }
        }
        [Association(@"DinhluongReferencesSanpham1")]
        public XPCollection<Dinhluong> Dinhluongs1 { get { return GetCollection<Dinhluong>(nameof(Dinhluongs1)); } }
        [Association(@"DinhluongReferencesSanpham"), Aggregated]
        public XPCollection<Dinhluong> Dinhluongs { get { return GetCollection<Dinhluong>(nameof(Dinhluongs)); } }
        [Association(@"TieuhaoReferencesSanpham"), Aggregated]
        public XPCollection<Tieuhao> Tieuhaos { get { return GetCollection<Tieuhao>(nameof(Tieuhaos)); } }
        [Association(@"DongnhapReferencesSanpham"), Aggregated]
        public XPCollection<Dongnhap> Dongnhaps { get { return GetCollection<Dongnhap>(nameof(Dongnhaps)); } }
        [Association(@"HoadonCTReferencesSanpham"), Aggregated]
        public XPCollection<HoadonCT> HoadonCTs { get { return GetCollection<HoadonCT>(nameof(HoadonCTs)); } }
    }

}
