//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CafeCMU.Module.BusinessObjects.ORMDataModel1
{

    public partial class Tieuhao : XPObject
    {
        Sanpham fSanphamID;
        [Association(@"TieuhaoReferencesSanpham")]
        public Sanpham SanphamID
        {
            get { return fSanphamID; }
            set { SetPropertyValue<Sanpham>(nameof(SanphamID), ref fSanphamID, value); }
        }
        HoadonCT fHoadonCTID;
        [Association(@"TieuhaoReferencesHoadonCT")]
        public HoadonCT HoadonCTID
        {
            get { return fHoadonCTID; }
            set { SetPropertyValue<HoadonCT>(nameof(HoadonCTID), ref fHoadonCTID, value); }
        }
        string fSoluong;
        public string Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<string>(nameof(Soluong), ref fSoluong, value); }
        }
        string fDongiaVon;
        public string DongiaVon
        {
            get { return fDongiaVon; }
            set { SetPropertyValue<string>(nameof(DongiaVon), ref fDongiaVon, value); }
        }
    }

}
